name: psctester
description: Mike and Ava's electric meter tester thing.

version: 1.2.4

environment:
  sdk: '>=3.9.0 <4.0.0'
  

dependencies:
  web: ^1.1.1 # Use the latest version
  intl: ^0.20.2
  http: ^1.5.0
  
dev_dependencies: 
  lints: ^6.0.0
  build_runner: ^2.8.0
  build_test: ^3.4.0
  build_web_compilers: ^4.2.3