name: psctester
description: Mike and Ava's electric meter tester thing.

version: 1.2.3

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  intl: ^0.18.0
  
dev_dependencies: 
  build_runner: ^2.3.2
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
