#!/bin/bash

# --- Setup Directories ---
echo "Creating new directory structure..."
mkdir -p backend cgi-bin web assets archive temp

# --- 1. Move Backend (Go) files ---
echo "Moving Go source files..."
# Move core Go files
[ -f main.go ] && mv main.go backend/
[ -f go.mod ] && mv go.mod backend/
[ -f go.sum ] && mv go.sum backend/
# Move compiled binary if it exists
[ -f psctester ] && mv psctester backend/
# Archive the experimental file
[ -f main_try1.go.try ] && mv main_try1.go.try backend/

# --- 2. Move Web Source (Dart/CSS/HTML) ---
echo "Moving Web source files..."
# We keep the original web folder but clean it up
[ -f psctester.dart ] && mv psctester.dart web/
[ -f psctester.css ] && mv psctester.css web/
[ -f index.html ] && mv index.html web/
[ -f analysis_options.yaml ] && mv analysis_options.yaml web/
[ -f pubspec.yaml ] && mv pubspec.yaml web/
[ -f pubspec.lock ] && mv pubspec.lock web/
[ -f build.yaml ] && mv build.yaml web/

# --- 3. Consolidate CGI-Bin ---
echo "Consolidating CGI scripts..."
# Copy from the web/cgi-bin (assuming it's most recent) to the root source
if [ -d "web/cgi-bin" ]; then
    cp -r web/cgi-bin/* cgi-bin/
    rm -rf web/cgi-bin
fi

# Cleanup old backups and links
rm -f cgi-bin.link 2>/dev/null  # Remove old symlink if named differently
[ -L cgi-bin ] && rm cgi-bin    # Remove symlink if it was named exactly 'cgi-bin'
[ -d cgi-bin.backup ] && mv cgi-bin.backup archive/

# --- 4. Move Assets (Images/Media) ---
echo "Moving assets..."
# Move from the web folder to the root assets folder
if [ -d "web/media" ]; then
    mv web/media/* assets/ 2>/dev/null
    rm -rf web/media
fi
# Move individual icons from web root
mv web/*.png assets/ 2>/dev/null
mv web/*.ico assets/ 2>/dev/null
mv web/*.webmanifest assets/ 2>/dev/null

# --- 5. Housekeeping & Cleanup ---
echo "Finalizing organization..."
# Move archives and releases
mv psctester_www.tar.gz archive/ 2>/dev/null
[ -d release ] && mv release/* archive/ && rmdir release

# Move logs/configs to temp or runtime
[ -f testlog.txt ] && mv testlog.txt temp/
[ -f control.json ] && mv control.json temp/

# Move documentation and versioning
[ -f README.txt ] && mv README.txt scripts/ 2>/dev/null
mv script_ver* scripts/ 2>/dev/null
mv version_tag.txt scripts/ 2>/dev/null

# --- 6. Remove Build Artifacts ---
# We delete these because they should be regenerated by 'webdev build'
echo "Cleaning up old build artifacts..."
rm -f web/*.js web/*.map web/*.deps

echo "------------------------------------------------"
echo "Done! Your project is now organized."
echo "Source code is in /backend and /web."
echo "Scripts are in /cgi-bin."
echo "Assets are in /assets."
echo "Run 'webdev build' to generate a fresh /build folder."